<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class('hsh-home'); ?>><?php wp_body_open(); ?>
<a class="hsh-skip" href="#hsh-main">本文へ移動</a>
<header class="hsh-header"><a class="hsh-brand" href="<?php echo esc_url(home_url('/')); ?>">ひろがる<span>趣味暮らし</span><small>HIROGARU SHUMI KURASHI</small></a><nav aria-label="主要カテゴリー"><?php foreach (hsh_topics() as $slug => $t) : ?><a href="<?php echo esc_url(hsh_category_url($slug)); ?>"><?php echo esc_html($t[0]); ?></a><?php endforeach; ?></nav></header>
<main id="hsh-main" class="hsh-main">
<section class="hsh-hero"><div class="hsh-hero-copy"><p class="hsh-eyebrow">好きなことから、暮らしがひろがる。</p><h1>猫と、<br>ウイスキーと、<br><span>自分らしい仕事。</span></h1><p class="hsh-intro">猫と過ごす日常。お気に入りの一杯。<br>ITの仕事と、個人で働く日々の工夫。<br>好きなことを大切にする、暮らしの記録です。</p><a class="hsh-button" href="#hsh-topics">好きなテーマから読む <span aria-hidden="true">↗</span></a></div>
<div class="hsh-art" role="img" aria-label="猫、ウイスキーグラス、パソコンを描いたイラスト"><svg viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><circle cx="310" cy="275" r="220" fill="#e4d9bc"/><path d="M40 460Q310 420 575 465L575 590H40Z" fill="#b28b61"/><rect x="320" y="320" width="195" height="119" rx="10" fill="#31584b"/><rect x="332" y="332" width="170" height="95" rx="4" fill="#eef0dc"/><path d="m380 364-20 18 20 18m75-36 20 18-20 18m-40-37-13 39" stroke="#587460" stroke-width="6" fill="none"/><path d="M303 440h227l-18 16H320Z" fill="#224337"/><path d="M130 405Q115 280 184 277Q261 285 245 417L264 464H112Z" fill="#765749"/><path d="M141 311l-10-94 53 43 61-36-7 102Q187 365 141 311" fill="#765749"/><path d="m140 240 8 45 22-19m43 0 22-20-3 43" fill="#dcb3a0"/><path d="M162 304q9-8 17 0m22 0q9-8 17 0" fill="none" stroke="#f7ead5" stroke-width="4" stroke-linecap="round"/><path d="m185 320 8 4-8 7" fill="#dcb3a0"/><path d="M138 430Q72 368 75 425Q74 474 149 459" fill="none" stroke="#765749" stroke-width="25" stroke-linecap="round"/><path d="m245 406 13 86h63l13-86Z" fill="#f7f2df" fill-opacity=".85" stroke="#fff7e9" stroke-width="4"/><path d="m251 444 7 45h63l7-45Z" fill="#bd7b30"/><path d="m264 439 15-12 18 15-14 14Z" fill="#fff5d9" fill-opacity=".7"/><path d="M408 171v67m-34-34h68M93 165v32m-16-16h32" stroke="#f8f1df" stroke-width="5" stroke-linecap="round"/></svg><span class="hsh-art-caption">SMALL JOYS, EVERY DAY.</span></div></section>
<section id="hsh-topics" class="hsh-topics"><div class="hsh-section-heading"><p class="hsh-eyebrow">EXPLORE YOUR INTERESTS</p><h2>気になることから。</h2></div><div class="hsh-topic-grid"><?php foreach (hsh_topics() as $slug => $t) : ?><a class="hsh-topic hsh-topic-<?php echo esc_attr($slug); ?>" href="<?php echo esc_url(hsh_category_url($slug)); ?>"><span class="hsh-topic-number"><?php echo esc_html($t[3]); ?></span><small><?php echo esc_html($t[2]); ?></small><h3><?php echo esc_html($t[0]); ?></h3><p><?php echo esc_html($t[1]); ?></p><span class="hsh-topic-link">記事を読む <span aria-hidden="true">↗</span></span></a><?php endforeach; ?></div></section>
<?php foreach (hsh_topics() as $slug => $t) : $posts = hsh_posts($slug); ?>
<section class="hsh-articles"><div class="hsh-article-heading"><div><p class="hsh-eyebrow"><?php echo esc_html($t[2]); ?></p><h2><?php echo esc_html($t[0]); ?></h2></div><a href="<?php echo esc_url(hsh_category_url($slug)); ?>">一覧を見る ↗</a></div><?php if ($posts) : ?><div class="hsh-post-grid"><?php foreach ($posts as $article) : ?><article><a href="<?php echo esc_url(get_permalink($article)); ?>"><?php if (has_post_thumbnail($article)) { echo get_the_post_thumbnail($article, 'medium_large', array('loading' => 'lazy')); } else { echo '<div class="hsh-post-placeholder" aria-hidden="true">' . esc_html($t[2]) . '</div>'; } ?><time datetime="<?php echo esc_attr(get_the_date('c', $article)); ?>"><?php echo esc_html(get_the_date('Y.m.d', $article)); ?></time><h3><?php echo esc_html(get_the_title($article)); ?></h3></a></article><?php endforeach; ?></div><?php else : ?><p class="hsh-empty">このテーマの記事は、これからお届けします。</p><?php endif; ?></section><?php endforeach; ?>
<section class="hsh-about"><p class="hsh-eyebrow">ABOUT THIS BLOG</p><h2>経験を、暮らしのヒントに。</h2><p>現在は1匹の猫と暮らし、これまで8匹の猫を最期まで見届けてきました。<br>MRとして働いた経験を経て、今は個人事業主としてIT・BPaaSの仕事に携わっています。</p><p>猫との日々、ウイスキーの楽しみ、仕事の工夫。<br>経験と確かめた情報をもとに、暮らしに役立つ記事をお届けします。</p></section>
</main><footer class="hsh-footer"><a href="<?php echo esc_url(home_url('/')); ?>">ひろがる趣味暮らし</a><nav aria-label="サイト情報"><?php $policy = get_privacy_policy_url(); if ($policy) : ?><a href="<?php echo esc_url($policy); ?>">プライバシーポリシー</a><?php endif; ?></nav><small>© <?php echo esc_html(wp_date('Y')); ?> ひろがる趣味暮らし</small></footer><?php wp_footer(); ?></body></html>
